### ISSUE TITLE
[Traefik Plugin Catalog] Plugin Analyzer has detected a problem.

### ISSUE THREAD

**Issue by traefiker** [SergioFloresG/traefik-cors-middleware#1]
The plugin was not imported into Traefik Plugin Catalog.

Cause:
```
failed to get the latest tag: missing tag/version
```
Traefik Plugin Analyzer will restart when you will close this issue.

If you believe there is a problem with the Analyzer or this issue is the result of a false positive, please contact [us](https://community.traefik.io/).

**Comment by SergioFloresG** [comment]
tag version https://github.com/SergioFloresG/corsmiddleware/releases/tag/v0.1.0

**Comment by SergioFloresG** [comment]
Version v0.1.0 - https://github.com/SergioFloresG/corsmiddleware/releases/tag/v0.1.0
